<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOmKRqat\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOmKRqat/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOmKRqat.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOmKRqat\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOmKRqat\App_KernelDevDebugContainer([
    'container.build_hash' => 'OmKRqat',
    'container.build_id' => 'c91364f7',
    'container.build_time' => 1717350772,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOmKRqat');
