<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTF79qi8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTF79qi8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTF79qi8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTF79qi8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTF79qi8\App_KernelDevDebugContainer([
    'container.build_hash' => 'TF79qi8',
    'container.build_id' => '630792f6',
    'container.build_time' => 1717349731,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTF79qi8');
